version: '3.8'

services:
  schedule_db:
    container_name: "schedule-db"
    image: postgres:16.0
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${SCHEDULE_DB_NAME}
      POSTGRES_USER: ${SCHEDULE_DB_USER}
      POSTGRES_PASSWORD: ${SCHEDULE_DB_PASSWORD}
    volumes:
      - scheduler_volume:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    expose:
      - "5432"
    networks:
      - appt-scheduler
  staff_db:
    container_name: "staff-db"
    image: postgres:16.0
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${STAFF_DB_NAME}
      POSTGRES_USER: ${STAFF_DB_USER}
      POSTGRES_PASSWORD: ${STAFF_DB_PASSWORD}
    volumes:
      - staff_volume:/var/lib/postgresql/data
    ports:
      - "5437:5432"
    expose:
      - "5432"
    networks:
      - appt-scheduler
  test_db:
    container_name: "test-db"
    image: postgres:16.0
    ports:
      - "5438:5432"
    expose:
      - "5432"
    networks:
      - appt-scheduler
  scheduler_1:
    build: ./schedule-ms
    image: rusnacam/scheduler:latest
    container_name: "schedule-ms-0"
    ports:
      - "3030:3030"
      - "40000:40000"
    depends_on:
      schedule_db:
        condition: service_started
      service_discovery:
        condition: service_started
    environment:
      - SVC_PORT=3030
      - SVC_HOST=schedule-ms-0
      - METRICS_PORT=40000
    networks:
      - appt-scheduler
  scheduler_2:
    build: ./schedule-ms
    image: rusnacam/scheduler:latest
    container_name: "schedule-ms-1"
    ports:
      - "3031:3031"
      - "40001:40001"
    depends_on:
      schedule_db:
        condition: service_started
      service_discovery:
        condition: service_started
    environment:
      - SVC_PORT=3031
      - SVC_HOST=schedule-ms-1
      - METRICS_PORT=40001
    networks:
      - appt-scheduler
  scheduler_3:
    build: ./schedule-ms
    image: rusnacam/scheduler:latest
    container_name: "schedule-ms-2"
    ports:
      - "3032:3032"
      - "40002:40002"
    depends_on:
      schedule_db:
        condition: service_started
      service_discovery:
        condition: service_started
    environment:
      - SVC_PORT=3032
      - SVC_HOST=schedule-ms-2
      - METRICS_PORT=40002
    networks:
      - appt-scheduler
  staff_1:
    build: ./staff-ms
    image: rusnacam/staff:latest
    container_name: "staff-ms-0"
    ports:
      - "8080:8080"
      - "50000:50000"
    depends_on:
      staff_db:
        condition: service_started
      service_discovery:
        condition: service_started
    environment:
      - SVC_PORT=8080
      - SVC_HOST=staff-ms-0
      - METRICS_PORT=50000
    networks:
      - appt-scheduler
  staff_2:
    build: ./staff-ms
    image: rusnacam/staff:latest
    container_name: "staff-ms-1"
    ports:
      - "8081:8081"
      - "50001:50001"
    tty:
      true
    depends_on:
      staff_db:
        condition: service_started
      service_discovery:
        condition: service_started
    environment:
      - SVC_PORT=8081
      - SVC_HOST=staff-ms-1
      - METRICS_PORT=50001
    networks:
      - appt-scheduler
  staff_3:
    build: ./staff-ms
    image: rusnacam/staff:latest
    container_name: "staff-ms-2"
    ports:
      - "8082:8082"
      - "50002:50002"
    tty:
      true
    depends_on:
      staff_db:
        condition: service_started
      service_discovery:
        condition: service_started
    environment:
      - SVC_PORT=8082
      - SVC_HOST=staff-ms-2
      - METRICS_PORT=50002
    networks:
      - appt-scheduler
  service_discovery:
    build: ./service-discovery
    image: rusnacam/service-discovery:latest
    container_name: "service-discovery"
    ports:
      - "5051:5051"
    networks:
      - appt-scheduler
  gateway:
    build: ./gateway
    image: rusnacam/gateway:latest
    container_name: "gateway"
    ports:
      - "5050:5050"
    expose:
      - "5050"
    tty:
      true
    depends_on:
      - service_discovery
    environment:
    - TIMEOUT=0.5
    networks:
      - appt-scheduler
  prometheus:
    image: prom/prometheus:v2.37.9
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_volume:/prometheus
    restart: unless-stopped
    networks:
      - appt-scheduler

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_volume:/var/lib/grafana
    restart: unless-stopped
    networks:
      - appt-scheduler
volumes:
  scheduler_volume:
    driver: local
  staff_volume:
    driver: local
  grafana_volume:
    driver: local
  prometheus_volume:
    driver: local

networks:
  appt-scheduler:
    driver: bridge