version: '3.8'

services:
  scheduler:
    build: ./schedule-ms
    container_name: "schedule-ms"
    ports:
      - "3030:3030"
    expose:
      - "3030"
    tty:
      true
    depends_on:
      - schedule_db
      - staff
      - service_discovery
      - gateway
  schedule_db:
    container_name: "schedule-db"
    image: postgres:16.0
    env_file:
      - .env
    environment:
      POSTGRES_DB: scheduler_svc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5436:5432"
    expose:
      - "5432"
  staff:
    build: ./staff-ms
    container_name: "staff-ms"
    ports:
      - "8080:8080"
    expose:
      - "8080"
    tty:
      true
    depends_on:
      - staff_db
      - service_discovery
      - gateway
  staff_db:
    container_name: "staff-db"
    image: postgres:16.0
    env_file:
      - .env
    environment:
      POSTGRES_DB: staff_svc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5437:5432"
    expose:
      - "5432"
  # service_discovery:
  #   build: ./service-discovery
  #   container_name: "service-discovery"
  #   ports:
  #     - "5051:5051"
  #   expose:
  #     - "5051"
  #   tty:
  #     true
  # gateway:
  #   build: ./gateway
  #   container_name: "gateway"
  #   ports:
  #     - "5050:5050"
  #   expose:
  #     - "5050"
  #   tty:
  #     true
  #   depends_on:
  #     - service_discovery

