// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.3
// source: api/scheduler/scheduler.proto

package scheduler

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Scheduler_CreateAppt_FullMethodName = "/Scheduler/CreateAppt"
	Scheduler_GetAppt_FullMethodName    = "/Scheduler/GetAppt"
	Scheduler_UpdateAppt_FullMethodName = "/Scheduler/UpdateAppt"
	Scheduler_DeleteAppt_FullMethodName = "/Scheduler/DeleteAppt"
	Scheduler_Check_FullMethodName      = "/Scheduler/Check"
)

// SchedulerClient is the client API for Scheduler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SchedulerClient interface {
	// Service Methods
	CreateAppt(ctx context.Context, in *CreateAppointment, opts ...grpc.CallOption) (*CreateResponse, error)
	GetAppt(ctx context.Context, in *GetAppointments, opts ...grpc.CallOption) (*GetResponse, error)
	UpdateAppt(ctx context.Context, in *UpdateAppointment, opts ...grpc.CallOption) (*UpdateResponse, error)
	DeleteAppt(ctx context.Context, in *DeleteAppointment, opts ...grpc.CallOption) (*DeleteResponse, error)
	// Health Check Methods
	Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type schedulerClient struct {
	cc grpc.ClientConnInterface
}

func NewSchedulerClient(cc grpc.ClientConnInterface) SchedulerClient {
	return &schedulerClient{cc}
}

func (c *schedulerClient) CreateAppt(ctx context.Context, in *CreateAppointment, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, Scheduler_CreateAppt_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) GetAppt(ctx context.Context, in *GetAppointments, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, Scheduler_GetAppt_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) UpdateAppt(ctx context.Context, in *UpdateAppointment, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, Scheduler_UpdateAppt_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) DeleteAppt(ctx context.Context, in *DeleteAppointment, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, Scheduler_DeleteAppt_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, Scheduler_Check_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchedulerServer is the server API for Scheduler service.
// All implementations must embed UnimplementedSchedulerServer
// for forward compatibility
type SchedulerServer interface {
	// Service Methods
	CreateAppt(context.Context, *CreateAppointment) (*CreateResponse, error)
	GetAppt(context.Context, *GetAppointments) (*GetResponse, error)
	UpdateAppt(context.Context, *UpdateAppointment) (*UpdateResponse, error)
	DeleteAppt(context.Context, *DeleteAppointment) (*DeleteResponse, error)
	// Health Check Methods
	Check(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedSchedulerServer()
}

// UnimplementedSchedulerServer must be embedded to have forward compatible implementations.
type UnimplementedSchedulerServer struct {
}

func (UnimplementedSchedulerServer) CreateAppt(context.Context, *CreateAppointment) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAppt not implemented")
}
func (UnimplementedSchedulerServer) GetAppt(context.Context, *GetAppointments) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAppt not implemented")
}
func (UnimplementedSchedulerServer) UpdateAppt(context.Context, *UpdateAppointment) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAppt not implemented")
}
func (UnimplementedSchedulerServer) DeleteAppt(context.Context, *DeleteAppointment) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAppt not implemented")
}
func (UnimplementedSchedulerServer) Check(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedSchedulerServer) mustEmbedUnimplementedSchedulerServer() {}

// UnsafeSchedulerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SchedulerServer will
// result in compilation errors.
type UnsafeSchedulerServer interface {
	mustEmbedUnimplementedSchedulerServer()
}

func RegisterSchedulerServer(s grpc.ServiceRegistrar, srv SchedulerServer) {
	s.RegisterService(&Scheduler_ServiceDesc, srv)
}

func _Scheduler_CreateAppt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAppointment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).CreateAppt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduler_CreateAppt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).CreateAppt(ctx, req.(*CreateAppointment))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_GetAppt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppointments)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).GetAppt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduler_GetAppt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).GetAppt(ctx, req.(*GetAppointments))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_UpdateAppt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAppointment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).UpdateAppt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduler_UpdateAppt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).UpdateAppt(ctx, req.(*UpdateAppointment))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_DeleteAppt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAppointment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).DeleteAppt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduler_DeleteAppt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).DeleteAppt(ctx, req.(*DeleteAppointment))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduler_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).Check(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Scheduler_ServiceDesc is the grpc.ServiceDesc for Scheduler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Scheduler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Scheduler",
	HandlerType: (*SchedulerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAppt",
			Handler:    _Scheduler_CreateAppt_Handler,
		},
		{
			MethodName: "GetAppt",
			Handler:    _Scheduler_GetAppt_Handler,
		},
		{
			MethodName: "UpdateAppt",
			Handler:    _Scheduler_UpdateAppt_Handler,
		},
		{
			MethodName: "DeleteAppt",
			Handler:    _Scheduler_DeleteAppt_Handler,
		},
		{
			MethodName: "Check",
			Handler:    _Scheduler_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/scheduler/scheduler.proto",
}
